title: "Dona Rita"
description: "Brazilian cheese bread. Pão de Queijo."
author: "Pedro Duarte"
email: oi@donarita.co.uk
url: "http://donarita.co.uk"
phone: "07952216979"
baseurl: ""


# Build settings
markdown: kramdown
permalink: /:categories/:title.html

# Custom
deliveryDate: "Sunday 15th October"
