title: "Dona Rita"
description: "Brazilian cheese breads/balls/buns/rolls. Pão de Queijo baked by Rita."
author: "Pedro Duarte"
email: oi@donarita.co.uk
url: "http://donarita.co.uk/"
phone: "07912950992"
baseurl: ""


# Build settings
markdown: kramdown
permalink: /:categories/:title.html
